//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.269
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemotePresentReceiver.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Up")]
        public global::System.Windows.Forms.Keys GamePadUp {
            get {
                return ((global::System.Windows.Forms.Keys)(this["GamePadUp"]));
            }
            set {
                this["GamePadUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Down")]
        public global::System.Windows.Forms.Keys GamePadDown {
            get {
                return ((global::System.Windows.Forms.Keys)(this["GamePadDown"]));
            }
            set {
                this["GamePadDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left")]
        public global::System.Windows.Forms.Keys GamePadLeft {
            get {
                return ((global::System.Windows.Forms.Keys)(this["GamePadLeft"]));
            }
            set {
                this["GamePadLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right")]
        public global::System.Windows.Forms.Keys GamePadRight {
            get {
                return ((global::System.Windows.Forms.Keys)(this["GamePadRight"]));
            }
            set {
                this["GamePadRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public global::System.Windows.Forms.Keys GamePadA {
            get {
                return ((global::System.Windows.Forms.Keys)(this["GamePadA"]));
            }
            set {
                this["GamePadA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public global::System.Windows.Forms.Keys GamePadB {
            get {
                return ((global::System.Windows.Forms.Keys)(this["GamePadB"]));
            }
            set {
                this["GamePadB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z")]
        public global::System.Windows.Forms.Keys GamePadX {
            get {
                return ((global::System.Windows.Forms.Keys)(this["GamePadX"]));
            }
            set {
                this["GamePadX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X")]
        public global::System.Windows.Forms.Keys GamePadY {
            get {
                return ((global::System.Windows.Forms.Keys)(this["GamePadY"]));
            }
            set {
                this["GamePadY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Space")]
        public global::System.Windows.Forms.Keys GamePadStart {
            get {
                return ((global::System.Windows.Forms.Keys)(this["GamePadStart"]));
            }
            set {
                this["GamePadStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tab")]
        public global::System.Windows.Forms.Keys GamePadSelect {
            get {
                return ((global::System.Windows.Forms.Keys)(this["GamePadSelect"]));
            }
            set {
                this["GamePadSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public global::System.Windows.Media.Color ScreenLaserColor {
            get {
                return ((global::System.Windows.Media.Color)(this["ScreenLaserColor"]));
            }
            set {
                this["ScreenLaserColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseTelnetPort {
            get {
                return ((bool)(this["UseTelnetPort"]));
            }
            set {
                this["UseTelnetPort"] = value;
            }
        }
    }
}
